name: Deploy

# TODO: Configure deployment workflow
# This workflow will be used to deploy the package to PyPI or other platforms

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Skip deployment (not configured)
        run: echo "Deploy workflow not configured yet."



